import * as fs from 'fs';
import * as path from 'path';
import { PathUtils } from '../utils/pathUtils';
import {
  HubItem,
  ItemType,
  TargetLocationConfig,
  FileWriteResult,
  SUBFOLDER_FILENAMES,
} from './types';

const GENERATED_MARKER = '<!-- Generated by AI Agent Hub — do not edit -->';

/**
 * Writes Hub content to agent target paths.
 *
 * Supports two file layouts:
 * - flat:      {path}/{item-name}.md
 * - subfolder: {path}/{item-name}/SKILL.md (or RULE.md, HOOK.md)
 *
 * All writes are constrained to a provided base directory
 * (workspace root for agent targets, repo root for repo-level sync)
 * to prevent path traversal.
 */
export class FileWriter {
  constructor(private readonly pathUtils: PathUtils) {}

  async write(
    items: readonly HubItem[],
    target: TargetLocationConfig,
    contentType: ItemType,
    basePath: string,
  ): Promise<FileWriteResult> {
    const filesWritten: string[] = [];
    const errors: string[] = [];

    const resolved = this.pathUtils.resolveSafeTarget(basePath, target.path);
    if (!resolved.ok) {
      errors.push(`Unsafe target path: ${resolved.reason}`);
      return { filesWritten, errors };
    }

    const targetDir = resolved.absolutePath;

    if (!fs.existsSync(targetDir)) {
      fs.mkdirSync(targetDir, { recursive: true });
    }

    for (const item of items) {
      const slug = slugify(item.name);
      let filePath: string;

      if (target.fileLayout === 'subfolder') {
        const dir = path.join(targetDir, slug);
        if (!fs.existsSync(dir)) {
          fs.mkdirSync(dir, { recursive: true });
        }
        filePath = path.join(dir, SUBFOLDER_FILENAMES[contentType]);
      } else {
        filePath = path.join(targetDir, `${slug}.${fileExtension(target.fileExtension)}`);
      }

      if (fs.existsSync(filePath) && !this.isHubGeneratedSync(filePath)) {
        errors.push(`Skipped (not hub-generated): ${filePath}`);
        continue;
      }

      const header = buildHeader(contentType);
      fs.writeFileSync(filePath, header + '\n\n' + item.content, 'utf-8');
      filesWritten.push(filePath);
    }

    return { filesWritten, errors };
  }

  async isHubGenerated(filePath: string): Promise<boolean> {
    if (!fs.existsSync(filePath)) return false;
    return fs.readFileSync(filePath, 'utf-8').includes(GENERATED_MARKER);
  }

  private isHubGeneratedSync(filePath: string): boolean {
    if (!fs.existsSync(filePath)) return false;
    return fs.readFileSync(filePath, 'utf-8').includes(GENERATED_MARKER);
  }
}

function buildHeader(contentType: ItemType): string {
  return [
    GENERATED_MARKER,
    `<!-- Hub Item Type: ${contentType} -->`,
    `<!-- Last synced: ${new Date().toISOString()} -->`,
  ].join('\n');
}

function slugify(name: string): string {
  return name
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function fileExtension(format: string): string {
  switch (format) {
    case 'mdc':
      return 'mdc';
    case 'instructions-md':
      return 'instructions.md';
    case 'prompt-md':
      return 'prompt.md';
    case 'md':
    default:
      return 'md';
  }
}
